name: Deploy

on:
  push:
    branches: main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      VITE_PRODUCT_API_URL: ${{ vars.VITE_PRODUCT_API_URL }}
      VITE_ORDERS_API_URL: ${{ vars.VITE_ORDERS_API_URL }}
      VITE_COGNITO_DOMAIN: ${{ vars.VITE_COGNITO_DOMAIN }}
      VITE_COGNITO_CLIENT_ID: ${{ vars.VITE_COGNITO_CLIENT_ID }}
      VITE_COGNITO_AUTHORITY: ${{ vars.VITE_COGNITO_AUTHORITY }}

      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      FROM_EMAIL: ${{ secrets.FROM_EMAIL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-south-1
          role-to-assume: arn:aws:iam::020529562828:role/GitHubActionsDeployRole

      - name: Build frontend
        run: pnpm build:frontend

      - name: Deploy CDK
        run: pnpm deploy:infra --require-approval never
